### PR TITLE
Corrected an indentation error

### PR DESCRIPTION
**Pull request by monocongo**
Fixes a mis-indentation bug which was causing a missing `n_threads` CLI argument to result in a TypeError, as described in issue #31

### CODE REVIEW

**Comment by keldrom** [comment]
@monocongo can you change only the line that you actually have modified? because like you have done I can't really understand where was the problem

**Comment by monocongo** [comment]
Sorry, it seems that the tabs were replaced by four spaces ([a good idea anyway](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/), but not the point of this fix).

See [this comment](https://github.com/EscVM/OIDv4_ToolKit/issues/31#issuecomment-482872378) in issue #31 for an explanation of what this PR fixes. When this indentation is fixed then the code works as advertised, otherwise, you will have errors like what is described in issue #31.

**Comment by dkendall100** [comment]
Oh darn, just opened another issue on this.

**Comment by keldrom** [comment]
Solved, thx

**Pull request closed without merging**
