### PR TITLE
Add function to get additional labels for downloaded images.

### PR DESCRIPTION
**Pull request by yu-jingrui**
I could not find a way to generate labels for other classes rather than the download class, so I implemented one. For example I want to download images of the class Tableware, but also want the annotations for Person in these images.

Also I did some changes to import so it is easier to debug.

### CODE REVIEW

**Comment by keldrom** [comment]
Why you don't have used the `--multiclass` option?

**Comment by fisheess** [comment]
> Why you don't have used the `--multiclass` option?

'--multiclass' option downloads images of all these classes

**Comment by keldrom** [comment]
I've don't actually understood your problem

**Comment by fisheess** [comment]
> I've don't actually understood your problem

For example, if I use 
`python main.py downloader --classes Apple Orange --type_csv train --multiclass 1`
then all images of classes Apple and Orange will be downloaded and labels for Apple and Orange are created as .txt in _Label_ folder. 
Some of these images contain other objects, such as Person. I want to create labels in the .txt files for class Person, but I do not want to download other images of class Person that do not have Apple or Orange in them.

**Comment by keldrom** [comment]
Ok, I'm in. But maybe this is a custom solution, maybe we can make another "downloader" or option capable of this action.

**Comment by fisheess** [comment]
I added the option '--additional_label_classes' to parser.py. It is optional. If it is not used downloader works just as was.

**Comment by startupgurukul** [comment]
nice feature, looking forward to the merge and also v5 support (maybe rethink the name the repo OID_ToolKit )

**Pull request closed without merging**
